vich_uploader:
    db_driver: orm

    mappings:
        product_images:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_images:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
